### ISSUE TITLE
get the blanck result files when using nanopore data

### ISSUE THREAD

**Issue by LileeGao** [zstephens/telogator#11]
I have my own nanppore DNA data
I use the telogator to explore TL
When I follow the pipline, I don't the the error infomation. But the tlens_by_chr.tsv file is empty just with the file header
and the violin.png is empty too

there is my commad:

minimap2 -ax map-ont -t 40 -N 5 -Y -L t2t-and-subtel.fa ${fqPath}/C02_C_clean.fq.gz | samtools view -bhS - > C02_C_aln-unsort.bam
samtools sort -o C02_C_aln.bam C02_C_aln-unsort.bam
samtools index C02_C_aln.bam

#get subset of reads that were mapped to subtelomere regions

python3 get_subtel_reads.py \
     --bam C02_C_aln.bam \
     --in-reads ${fqPath}/C02_C_clean.fq.gz \
     --out-reads C02_C_subtel-reads.fa.gz

####align read subset to telogator reference

winnowmap -W resources/repetitive_k15.txt \
   -ax map-ont \
   -Y \
    resources/t2t-telogator-ref.fa \
    C02_C_subtel-reads.fa.gz \
    | samtools view -bh > C02_C_subtel_aln-unsort.bam

samtools sort -o C02_C_subtel_aln.bam C02_C_subtel_aln-unsort.bam
samtools index C02_C_subtel_aln.bam
rm C02_C_subtel_aln-unsort.bam

#run telogator on subtel-only alignment

python3 telogator.py -i C02_C_subtel_aln.bam -o C02_C_telogator_out/

**Comment by zstephens** [comment]
Is there any information that telogator prints to console? It should provide some statistics about read counts and filters as it processes the reads. Aside from that there isn't much info to go off of here, could you validate that the C02_C_subtel_aln.bam input file contains reads?

**Comment by LileeGao** [comment]
Thank you for your response. Here is my log files. 
And I use samtools view C02_C_subtel_aln.bam| wc -l to see the number of the reads. The number is 118125.
The command is
 python3 telogator.py -i C02_C_subtel_aln.bam -o C02_C_telogator/ -r ont -k kmers.tsv
Now I get one line in the tlens_by_chr.tsv

#chr    position        TL_max  read_TLs        read_lengths
chr7p   3907    1088    268,303,752,1088        8819,6190,10944,27600

#####
using user-specified kmer list: kmers.tsv
getting all read data from input alignment... (136 sec)
initial read filtering... (308 sec)
 - 66114 --> 51142 reads
identify anchorable telomeres... (356 sec)
 - 51142 --> 75 reads

reads filtered:
 - min_readlen 13206
 - min_telbases 756
 - no_anchored_tel 51059
 - no_chr_aln 3
 - pq_mix 1
 - trim_filter 7
 - unexplained_seq 7
 - unmapped 1000

removing anchored tels that double-anchored according to other reads... (0 sec)
 - 75 --> 32 reads
removing reads with tel regions that are insufficiently canonical... (0 sec)
 - 32 --> 32 reads
clustering anchored tels by position & filtering by read count...
 - chr1p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr1q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr2q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr3p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr5q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr7p: 1 anchor / 4 read
 - chr7q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr8p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr8q: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr9q: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr11p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr11q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr12p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr13q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr15p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr15q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr16p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr18q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr21p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr21q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr22p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chrXp: 1 anchor / 2 read --> 0 anchor / 0 read
writing TL results to "tlens_by_chr.tsv"...
creating violin plots...
using user-specified kmer list: kmers.tsv
getting all read data from input alignment... (136 sec)
initial read filtering... (301 sec)
 - 66114 --> 51142 reads
identify anchorable telomeres... (349 sec)
 - 51142 --> 75 reads
reads filtered:
 - min_readlen 13206
 - min_telbases 756
 - no_anchored_tel 51059
 - no_chr_aln 3
 - pq_mix 1
 - trim_filter 7
 - unexplained_seq 7
 - unmapped 1000

removing anchored tels that double-anchored according to other reads... (0 sec)
 - 75 --> 32 reads
removing reads with tel regions that are insufficiently canonical... (0 sec)
 - 32 --> 32 reads
clustering anchored tels by position & filtering by read count...
 - chr1p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr1q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr2q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr3p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr5q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr7p: 1 anchor / 4 read
 - chr7q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr8p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr8q: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr9q: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr11p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr11q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr12p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr13q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr15p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr15q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr16p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr18q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr21p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr21q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr22p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chrXp: 1 anchor / 2 read --> 0 anchor / 0 read
writing TL results to "tlens_by_chr.tsv"...
creating violin plots...
#############

**Comment by zstephens** [comment]
Thanks for providing this log! What I think is happening is that Nanopore data tends to systematically misrepresent telomere repeats as other sequences (see [this paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02751-6) for more details), and the current kmer set that Telogator uses does not include these, so it is not finding the telomere regions.

Telogator previously had support for these additional kmers, but I forgot to reimplement them after refactoring the code to its current version. I will add that feature back in, and will follow up with you here once it is implemented.

**Comment by zstephens** [comment]
Greetings, I added nanopore-specific kmers back in the latest commit (b09659c1c2e37807f346a7a2f3f363a68d24f561), and they should be used whenever the `-r ont` input option is specified. Could you try reprocessing your data?

**Comment by LileeGao** [comment]
Thank you very much for your help. I tried again with the following code, but it didn't show the telomere lengths for all chromosomes.
the commad is this:

python3 telogator-main/telogator.py \
       -i C02_C_subtel_aln_fq.bam \
       -o C02_C_telogator_fq/ -r ont \
       -k /telogator-main/resources/kmers.tsv

the result like this:
#chr    position        TL_p90  read_TLs        read_lengths
chr7p   3907    1001    280,312,777,1098        8819,6190,10944,27600
chr15p  6068    4788    276,355,655,3054,5944   25350,13818,15607,23003,22297
chr15q  497003  1105    302,305,1306    17811,26858,24594
chr18q  496395  3225    267,306,1083,4143       13243,16565,12032,21867
chr21p  3009    5561    798,2084,6431   17982,16182,7559

AND the log information like this:
using user-specified kmer list: kmers.tsv
getting all read data from input alignment... (139 sec)
initial read filtering... (2151 sec)
 - 66114 --> 51898 reads
identify anchorable telomeres... (372 sec)
 - 51898 --> 242 reads

reads filtered:
 - min_readlen 13206
 - no_anchored_tel 51450
 - no_chr_aln 3
 - nontel_kmer_dens 141
 - pq_mix 1
 - tel_frac 42
 - trim_filter 7
 - unexplained_seq 22
 - unmapped 1000

removing anchored tels that double-anchored according to other reads... (0 sec)
 - 242 --> 86 reads
removing reads with tel regions that are insufficiently canonical... (0 sec)
 - 86 --> 53 reads
clustering anchored tels by position & filtering by read count...
 - chr1p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr2q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr3p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr3q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr4p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr5p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr5q: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr7p: 2 anchor / 5 read --> 1 anchor / 4 read
 - chr7q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr8p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr8q: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr9q: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr10p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr11p: 2 anchor / 3 read --> 0 anchor / 0 read
 - chr12p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr12q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr13q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr15p: 1 anchor / 5 read
 - chr15q: 1 anchor / 3 read
 - chr16p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr17p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chr17q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr18q: 1 anchor / 4 read
 - chr20p: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr21p: 1 anchor / 3 read
 - chr21q: 1 anchor / 1 read --> 0 anchor / 0 read
 - chr22p: 1 anchor / 2 read --> 0 anchor / 0 read
 - chrXp: 1 anchor / 2 read --> 0 anchor / 0 read
writing TL results to "tlens_by_chr.tsv"...
creating violin plots...

**Comment by zstephens** [comment]
The only other thing I can think to try at this point would be to lower some of the quality control filters from their default values. I just pushed a new commit (5dfc5fe88b141e8bbc48410ed6729bf3e46bda88) that adds some input options which might be useful here. I suggest adding the following input arguments:

`-fc 0.05` - reduces the threshold of the "insufficiently canonical" filter
`-cr 1` - reduces the read count requirement for outputting TL from 3 to 1
`--no-anchorfilt` - disables the double-anchor filtering step

This will almost certainly result in some false positives, but it will hopefully at least some results so that you can get a general idea of what the telomeres of your sample look like.

**Comment by zstephens** [comment]
Oh, I also wanted to mention that in order to reduce computation time, you can specify use `-i tel-data.p` instead of reprocessing the BAM file each time.

**Comment by LileeGao** [comment]
I apologize for the delayed response, and thank you very much for your assistance.
I'll try again about the commond like:
python3 telogator-main/telogator.py \
       -i  /C02_C_telogator_fq/tel-data.p \
       -o C02_C_telogator_fq/ -r ont \
       -k  /telogator-main/resources/kmers.tsv \
       -fc 0.05 \
       -cr 1 \
       --no-anchorfilt

And I get the file like this:
#chr    position        TL_p90  read_TLs        read_lengths
chr1p   3002    625     625     16486
chr1p   220437  4799    275,426,1617,2438,4129,4220,4309,4433,4471,4799,5573    15472,11242,13475,13189,13247,15711,8386,12876,17678
,12161,21840
chr1p   305763  1627    1627    14278
chr1q   311969  724     724     17127
chr2q   203829  2038    494,2210        13056,16271
chr2q   302495  2161    863,1048,1285,1454,1947,2376    18737,5958,15072,16477,11337,13848
chr2q   489763  799     799     26900
chr3p   3253    257     257     18481
chr3p   456725  894     894     14144
chr3q   495221  486     486     9454
chr4p   3401    343     343     13108
chr4q   270915  1038    1038    17691
chr5p   2612    710     710     8625
chr5p   41169   552     552     16316
chr5p   327516  10895   10895   23073
chr5p   421467  1350    459,937,987,1026,1566   8515,15176,19827,6039,11620
chr5q   46490   586     586     45796
chr5q   497838  310     283,314 21237,14656
chr7p   3907    1001    280,312,777,1098        8819,6190,10944,27600
chr7p   114595  710     710     26482
chr7p   212974  9632    9632    26942
chr7p   500001  1232    1232    14858
chr7q   145977  962     962     14238
chr7q   496368  690     690     8047
chr8p   2408    303     303     11765
chr8q   494672  1417    406,1530        14241,20593
chr9q   496462  307     295,309 19444,13303
chr10p  3102    706     278,754 26508,11228
chr10q  229820  865     865     5406
chr10q  259854  442     442     20723
chr10q  424411  1234    1234    23126
chr11p  2435    4572    280,5049        26291,12161
chr11p  202756  846     846     5616
chr11q  421376  335     335     15260
chr12p  3720    381     302,390 29211,29165
chr12p  215122  276     276     7230
chr12q  497453  302     302     18697
chr13p  16420   552     552     17086
chr13p  55679   3961    3961    24595
chr13p  59713   7817    7817    19867
chr13p  64407   15874   3901,3970,4045,4625,5680,5750,6129,7149,7649,7787,9653,9703,10118,10757,12285,12927,13040,13425,13527,14203,15793,15909,16794,17098     11601,12878,24072,12579,9419,12094,23032,18852,16001,18025,12352,17072,12364,15460,19788,17345,18607,19708,17731,17400,20214,17951,30235,21576
chr13p  467608  277     277     38705
chr13q  240290  1215    1215    22718
chr13q  496178  6774    6774    9019
chr14q  466822  384     384     5412
chr15p  6068    4788    276,355,655,3054,5944   25350,13818,15607,23003,22297
chr15q  46574   2833    742,849,2501,2976       12848,9113,10825,10167
chr15q  497003  1105    302,305,1306    17811,26858,24594
chr16p  3153    1950    940,2063        24359,17520
chr16p  12817   395     283,408 19789,9377
chr16p  393630  409     409     13343
chr17p  2206    1335    255,1455        28077,20364
chr17q  372849  2631    627,756,2242,2393,2791  25742,20192,18358,15460,16262
chr17q  396099  3103    3103    8766
chr18p  467454  6500    6500    19060
chr18q  496395  3225    267,306,1083,4143       13243,16565,12032,21867
chr19p  393916  2763    337,794,1629,2657,2835  21490,8399,8066,24258,11342
chr19p  416446  2239    791,1524,2418   12903,11465,20238
chr20p  6514    1509    321,1641        18279,16342
chr21p  3009    5561    798,2084,6431   17982,16182,7559
chr21p  220800  649     649     8245
chr21q  106677  606     461,623 15194,6169
chr21q  494570  374     374     19840
chr22p  4601    1849    1430,1896       11482,15776
chrXp   2001    5118    1603,5509       14288,12781
chrXp   458373  269     269     11565
chrYp   403190  1553    1103,1603       26966,11322
chrYp   420596  388     388     22814
chrYq   104449  2291    286,876,2645    18948,20629,22294


And the log files like；
using user-specified kmer list: kmers.tsv
reading pickle input...
removing reads with tel regions that are insufficiently canonical... (0 sec)
 - 242 --> 155 reads
clustering anchored tels by position & filtering by read count...
 - chr1p: 3 anchor / 13 read
 - chr1q: 1 anchor / 1 read
 - chr2q: 3 anchor / 9 read
 - chr3p: 2 anchor / 2 read
 - chr3q: 1 anchor / 1 read
 - chr4p: 1 anchor / 1 read
 - chr4q: 1 anchor / 1 read
 - chr5p: 4 anchor / 8 read
 - chr5q: 2 anchor / 3 read
 - chr7p: 4 anchor / 7 read
 - chr7q: 2 anchor / 2 read
 - chr8p: 1 anchor / 1 read
 - chr8q: 1 anchor / 2 read
 - chr9q: 1 anchor / 2 read
 - chr10p: 1 anchor / 2 read
 - chr10q: 3 anchor / 3 read
 - chr11p: 2 anchor / 3 read
 - chr11q: 1 anchor / 1 read
 - chr12p: 2 anchor / 3 read
 - chr12q: 1 anchor / 1 read
 - chr13p: 5 anchor / 28 read
 - chr13q: 2 anchor / 2 read
 - chr14q: 1 anchor / 1 read
 - chr15p: 1 anchor / 5 read
 - chr15q: 2 anchor / 7 read
 - chr16p: 3 anchor / 5 read
 - chr17p: 1 anchor / 2 read
 - chr17q: 2 anchor / 6 read
 - chr18p: 1 anchor / 1 read
 - chr18q: 1 anchor / 4 read
 - chr19p: 2 anchor / 8 read
 - chr20p: 1 anchor / 2 read
 - chr21p: 2 anchor / 4 read
 - chr21q: 2 anchor / 3 read
 - chr22p: 1 anchor / 2 read
 - chrXp: 2 anchor / 3 read
 - chrYp: 2 anchor / 3 read
 - chrYq: 1 anchor / 3 read
writing TL results to "tlens_by_chr.tsv"...
creating violin plots...
 I think this might be the final result. Do you see any room for improvement?

**Comment by zstephens** [comment]
After looking at a few nanopore datasets, I found that legitimate (albeit extremely noisy) telomere reads were being caught by the "pq mix" filter, so as of commit a625655c0c9154955a54cfcf44f7ca7e03259123 I disabled this filter if `-r ont` is specified. Looking at you logs above it doesn't appear as though this will have much effect, but in some internal datasets I found it increased the number of telomere reads by 30-40%
