### ISSUE TITLE
IMPORTANT REFERENCE

### ISSUE THREAD

**Issue by jake-bioinfo** [zstephens/telogator#13]
Sorry you closed the previous issue, but I see you didn't add the reference to your github page. I believe as a fellow academic you understand the importance of giving credit to ideas/concepts. 

YOU NEED TO REFERENCE ON YOUR GITHUB PAGE 
github: https://github.com/jake-bioinfo/tld
paper: Reed J, Kirkman LA, Kafsack BF, Mason CE, Deitsch KW. Telomere length dynamics in response to DNA damage in malaria parasites. iScience. 2021 Jan 20;24(2):102082. doi: 10.1016/j.isci.2021.102082. PMID: 33644714; PMCID: PMC7887396.

You need to cite relevant previous work, as well as any work (dependencies) which your work depends on. 

Best, 
Jake

**Comment by zstephens** [comment]
We have cited this work in our most recent publication: https://link.springer.com/article/10.1186/s12859-024-05807-5
