### ISSUE TITLE
Using telogator with Oxford Nanopore sequence data?

### ISSUE THREAD

**Issue by santiago-es** [zstephens/telogator#3]
Hi,

I'm a grad student attempting to use telogator with my long-read nanopore sequencing data, thanks in advance for your help. I'm fairly new to any kind of bioinformatic work. 

Is the python script as-is compatible with Nanopore sequencing data? I don't see a reason why it wouldn't be, however after aligning my data with pbmm2 as directed, the grab_*** script returns nothing in the .fq output and I have trouble believing there are zero subtelomeric reads anywhere in the data.

I figure I should probably not use pbmm2 aligner since its built for PacBio and use minimap2 standalone instead, but my first attempt at that also yielded an empty fastq file following grab_****

I am attaching the input aln.bam / aln.bam.bai (created by aligning with pbmm2) and reads file I am attempting to do this with in a zip file (telogator_example). GDrive link because its 1.56 Gb. 

Thanks! 
https://drive.google.com/file/d/1EBIyuiIdPliEWTJZttagCu_vbyZjF_nP/view?usp=sharing

**Comment by zstephens** [comment]
Greetings, in a recent issue thread I posted the series of commands I used to process Nanopore reads with Telogator. You might find this useful: https://github.com/zstephens/telogator/issues/2#issuecomment-1060069447

In this case however it looks like the issue is because `grab_reads_from_subtel_aln.py` expects the input to be in fasta format, not fastq. That is a bit inconvenient so I definitely will add support for fastq input soon. In the meantime you might be able to proceed by converting your fastq to fasta and feeding that to the script instead. Here is an example of how you could accomplish that:

`zcat mcf10a.fq.gz | paste - - - - | cut -f 1,2 | sed 's/@/>/'g | tr -s "\t" "\n" | gzip > mcf10a.fa.gz`

**Comment by zstephens** [comment]
As an update: I added support for .fq/.fq.gz input in `grab_reads_from_subtel_aln.py` in commit e17837f0774d34744291c1bafb5ba70936f41f1d

**Comment by santiago-es** [comment]
Thank you! I will try this. I'm currently running Grab.py with the fasta modification you suggested. It's been running for the past ~6h or so but it's a big file. If It's not complete by the morning on my machine I'll restart and rebuild the new commit

**Comment by santiago-es** [comment]
I've run it with both fa and fq original reads file, also before and after porechop but don't seem to have any success with telomere measurement. I imagine this is a problem with the underlying data and not the pipeline? By the way, if youre able to send a PDF of the full-text paper that would be great as my university library only sources the abstract from Bioinformatics but not the full text. 

Thanks!

**Comment by zstephens** [comment]
Was the data you had linked above the entire fq, or just a subset? If so I can try to run it on my end to see where something might be going awry.

[link removed after download]

**Comment by santiago-es** [comment]
The data I linked above is the entire fq for that particular sample, yes. I generated it by concatenating the individual Fqs from the nanopore output into one large file. Thanks for the manuscript! Let me know if you are able to see results if any, I appreciate it.

**Comment by zstephens** [comment]
I was able to successfully run telogator on this data, however, the coverage is far too low to say anything about telomeres. Of the ~50k reads, only 500 map to subtelomeres, and there were basically no reads containing telomere sequence. Sorry to report that I could not tell you anything about this sample's telomeres.
